### ISSUE TITLE
Colors for default pronouns?

### ISSUE THREAD

**Issue by tasonosenshi** [ashhhleyyy/player-pronouns#1]

**Comment by tasonosenshi** [comment]
It would be nice to be able to format the default pronouns to add color.  Maybe instead of implicitly always including them, explicitly include them in the config file so they can be modified?

**Comment by tasonosenshi** [comment]
It should be noted, that while placeholder formatting works, the raw placeholder text shows up in the list.  I'm using standard minecraft formatting codes to make it render correctly in the list.

```json
{
  "allow_custom": false,
  "single": [],
  "pairs": [
        "§dshe§r",
    ]
}
```

![image](https://user-images.githubusercontent.com/45836420/128449376-cf274407-03ec-4699-bce9-2237482853aa.png)

**Comment by ashhhleyyy** [comment]
Look like an interesting concept, I'll have a look at implementing this along with a couple of other internal improvements for a 1.1.0 release :smile:

**Comment by ashhhleyyy** [comment]
Added in [1.1.0](https://github.com/ashisbored/player-pronouns/releases/tag/v1.1.0)!
