### ISSUE TITLE
Not working on 1.19.3

### ISSUE THREAD

**Issue by Lou9896** [ashhhleyyy/player-pronouns#11]
I followed all instructions to set up this mod for Styled player list and tab list on my server and now names just show up with [Unknown] as their pronouns no matter what I do

**Comment by ashhhleyyy** [comment]
I haven't been maintaining this mod as well as I'd liked, so I've skipped the later 1.19 releases and merged #12 to support 1.20 for the next release.
#10 should still work if you'd like a version compatible with 1.19.3 😄
