### ISSUE TITLE
not working, or I'm just not understanding

### ISSUE THREAD

**Issue by ThatsJustAsh** [ashhhleyyy/player-pronouns#17]
For some reason, prnouns just don't show up for me in chat or in the player list.
![image](https://github.com/user-attachments/assets/c10d4d17-0deb-41ab-af67-7ce16d82dd3f)
I apologize if this is the wrong place, wasn't sure where else to post this

**Comment by ashhhleyyy** [comment]
ah sorry, i meant to reply to this (i am very easily distracted unfortunately)
the mod itself doesn't include features to display pronouns anywhere, it's designed to integrate with other mods like [styled chat](https://modrinth.com/mod/styled-chat) or [styled player list](https://modrinth.com/mod/styledplayerlist). there's a couple of examples for those two mods [in the readme](https://github.com/ashhhleyyy/player-pronouns?tab=readme-ov-file#displaying-pronouns)

**Comment by ThatsJustAsh** [comment]
Don't worry about being distracted, I didn't expect a replay right after I made the post anyway.

Yeah, I figured it out, hence why I closed this myself as it was user-error. However, I think having a direct thing saying "hey, this mod does not work on it's own and require the use of styledchat and styledplayerlist" would clear up the confusion, at least for people who might run into the same thing I was dealing with.

**Comment by ashhhleyyy** [comment]
yeah i agree

i've updated the github readme, and the modrinth description to hopefully better clarify that other mods are required - hopefully they're a bit less vague now (especially the modrinth one, which mentioned the other mods, but only with screenshots and not mentioning that you need them to set it up)
