### ISSUE TITLE
Typo in default pronouns list

### ISSUE THREAD

**Issue by Zeklandia** [ashhhleyyy/player-pronouns#20]
Line 11 of `default_pronouns.json` has the possessive form of 'its' as the object pronoun. That line should be: `"it", "it",`.

**Comment by ashhhleyyy** [comment]
hiya!
this isn't a typo, most pronoun sites format these as `it/its` (see [PronounDB.org](https://pronoundb.org/wiki/api-docs#sets), [pronouns.page](https://en.pronouns.page/it)), so I feel this is a reasonable format (the alternative being `it/it's`, which doesn't look great)
