### ISSUE TITLE
Cannot unset pronouns

### ISSUE THREAD

**Issue by solonovamax** [ashhhleyyy/player-pronouns#3]
It would be nice if a `/pronouns unset`, or `/pronouns clear` command was added in case someone wanted to, for some reason, clear their pronouns.

**Comment by ashhhleyyy** [comment]
I'll take a look at adding this over the weekend :)

**Comment by ashhhleyyy** [comment]
Fixed in c860c11
Released as [v1.4.0+1.18](https://github.com/ashhhleyyy/player-pronouns/releases/tag/v1.4.0+1.18) ([modrinth](https://modrinth.com/mod/player-pronouns/version/QTHCNGjQ))
