### ISSUE TITLE
1.19 support

### ISSUE THREAD

**Issue by ashhhleyyy** [ashhhleyyy/player-pronouns#4]
Minecraft 1.19 was released and I should probably update

**Comment by JustPyrrha** [comment]
open to PRs? might have a crack at it over the weekend
edit: mainly cause i wanna use it on a 1.19 server

**Comment by ashhhleyyy** [comment]
Yeah, feel free!
I'm away over the weekend and I didn't have any particular plans on when I wanted to get this done anyway

**Comment by ashhhleyyy** [comment]
Released as [v1.5.0+1.19](https://github.com/ashhhleyyy/player-pronouns/releases/tag/v1.5.0+1.19)!
